version: 5.0.{build}
skip_tags: true

image: Visual Studio 2022

build_script:
- cmd: nuget pack MSBuild.PublishNuget.Target.nuspec -Version %APPVEYOR_BUILD_VERSION%

artifacts:
- path: '**\*nupkg'
  name: Package
  
deploy:
- provider: Environment
  name: NuGet
  on:
   branch: main
  artifact: Package
  
- provider: GitHub
  on:
   branch: main
  tag: $(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  force_update: true
  artifact: Package
