version: 1.1.{build}
skip_tags: true
image: Visual Studio 2017
build_script:
- cmd: nuget pack MSBuild.PublishNuget.Target.nuspec -Version %APPVEYOR_BUILD_VERSION%
artifacts:
- path: '**\*nupkg'
deploy:
- provider: Environment
  name: NuGet
  artifact: Package
